// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUX_RX5aNZW30znhj5P8zIB8d9yHh50zw',
    appId: '1:449989823503:web:2f67af46dc1c043c33a77a',
    messagingSenderId: '449989823503',
    projectId: 'appflutter-27527',
    authDomain: 'appflutter-27527.firebaseapp.com',
    databaseURL: 'https://appflutter-27527-default-rtdb.firebaseio.com',
    storageBucket: 'appflutter-27527.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi3OSMEwKoqqaDnukXPApljfaSNMbcLbI',
    appId: '1:449989823503:android:52a65a5d4509259033a77a',
    messagingSenderId: '449989823503',
    projectId: 'appflutter-27527',
    databaseURL: 'https://appflutter-27527-default-rtdb.firebaseio.com',
    storageBucket: 'appflutter-27527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6zoRKUilSdQk1L-86jLpAxbG4no1YEuU',
    appId: '1:449989823503:ios:df4cc0c99c3bd19f33a77a',
    messagingSenderId: '449989823503',
    projectId: 'appflutter-27527',
    databaseURL: 'https://appflutter-27527-default-rtdb.firebaseio.com',
    storageBucket: 'appflutter-27527.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6zoRKUilSdQk1L-86jLpAxbG4no1YEuU',
    appId: '1:449989823503:ios:4b64439468ef0a0933a77a',
    messagingSenderId: '449989823503',
    projectId: 'appflutter-27527',
    databaseURL: 'https://appflutter-27527-default-rtdb.firebaseio.com',
    storageBucket: 'appflutter-27527.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
